homepage:
    path: /register
    controller: App\Controller\RegistrationController::register
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

