homepage:
    path: /spotlight
    controller: App\Controller\SpotlightController::getSpotlight
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

